apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesseract
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tesseract
  template:
    metadata:
      labels:
        name: tesseract
    spec:
      serviceAccountName: tesseract
      containers:
        - name: tesseract
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - tesseract
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tesseract"
