kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tesseract
subjects:
- kind: ServiceAccount
  name: tesseract
roleRef:
  kind: Role
  name: tesseract
  apiGroup: rbac.authorization.k8s.io
